"""
ChromaDB vector store service.

Provides CRUD operations over a local persistent ChromaDB collection
using embeddings generated by the embedder service.
"""

from __future__ import annotations

import uuid
from typing import Any, Dict, List, Optional

import chromadb
from chromadb.config import Settings as ChromaSettings

from app.core.config import get_settings
from app.core.logger import get_logger
from app.services import embedder as embedder_svc

logger = get_logger(__name__)

# Module-level ChromaDB client singleton
_client: Optional[chromadb.PersistentClient] = None


def _get_client() -> chromadb.PersistentClient:
    """Return (or create) the persistent ChromaDB client."""
    global _client
    if _client is None:
        settings = get_settings()
        persist_dir = settings.chroma_persist_dir
        logger.info(f"Connecting to ChromaDB at: {persist_dir}")
        _client = chromadb.PersistentClient(
            path=persist_dir,
            settings=ChromaSettings(anonymized_telemetry=False),
        )
    return _client


def get_or_create_collection(name: Optional[str] = None) -> chromadb.Collection:
    """
    Return an existing ChromaDB collection or create it if absent.

    Args:
        name: Collection name (defaults to CHROMA_COLLECTION_NAME from config).

    Returns:
        chromadb.Collection instance.
    """
    settings = get_settings()
    collection_name = name or settings.chroma_collection_name
    client = _get_client()
    collection = client.get_or_create_collection(
        name=collection_name,
        metadata={"hnsw:space": "cosine"},  # cosine similarity
    )
    logger.debug(f"Using collection '{collection_name}' ({collection.count()} docs)")
    return collection


def add_documents(
    chunks: List[str],
    metadatas: List[Dict[str, Any]],
    ids: Optional[List[str]] = None,
    collection_name: Optional[str] = None,
) -> None:
    """
    Embed and store text chunks in ChromaDB.

    - Generates embeddings in one batch call.
    - Inserts in groups of 100 to avoid memory spikes.
    - Deduplicates by ID (existing IDs are skipped).

    Args:
        chunks:          Text strings to embed and store.
        metadatas:       One metadata dict per chunk.
        ids:             Optional explicit IDs; auto-generated (UUID4) if omitted.
        collection_name: Override the default collection name.
    """
    if not chunks:
        logger.warning("add_documents called with empty chunks list — nothing to do.")
        return

    if len(chunks) != len(metadatas):
        raise ValueError(
            f"chunks ({len(chunks)}) and metadatas ({len(metadatas)}) must have the same length."
        )

    # Auto-generate IDs if not provided
    if ids is None:
        ids = [str(uuid.uuid4()) for _ in chunks]
    elif len(ids) != len(chunks):
        raise ValueError(
            f"ids ({len(ids)}) and chunks ({len(chunks)}) must have the same length."
        )

    collection = get_or_create_collection(collection_name)

    # Deduplicate: find which IDs already exist
    existing_ids: set[str] = set()
    try:
        existing = collection.get(ids=ids, include=[])
        existing_ids = set(existing["ids"])
    except Exception:  # noqa: BLE001
        pass  # collection may be empty; proceed

    new_mask = [i for i, doc_id in enumerate(ids) if doc_id not in existing_ids]
    if not new_mask:
        logger.info("All documents already exist in collection — skipping insert.")
        return

    new_chunks    = [chunks[i]    for i in new_mask]
    new_metadatas = [metadatas[i] for i in new_mask]
    new_ids       = [ids[i]       for i in new_mask]

    logger.info(f"Embedding {len(new_chunks)} new chunks (batch size 100)…")

    # Batch-insert in groups of 100
    BATCH_SIZE = 100
    for batch_start in range(0, len(new_chunks), BATCH_SIZE):
        batch_chunks    = new_chunks[batch_start : batch_start + BATCH_SIZE]
        batch_metas     = new_metadatas[batch_start : batch_start + BATCH_SIZE]
        batch_ids       = new_ids[batch_start : batch_start + BATCH_SIZE]

        batch_embeddings = embedder_svc.embed(batch_chunks)

        collection.add(
            documents=batch_chunks,
            embeddings=batch_embeddings,
            metadatas=batch_metas,
            ids=batch_ids,
        )
        logger.debug(
            f"  Inserted batch {batch_start // BATCH_SIZE + 1} "
            f"({len(batch_chunks)} docs)"
        )

    logger.info(f"Stored {len(new_chunks)} new documents in ChromaDB.")


def similarity_search(
    query: str,
    k: int = 5,
    where: Optional[Dict[str, Any]] = None,
    collection_name: Optional[str] = None,
) -> List[Dict[str, Any]]:
    """
    Search the collection for the *k* most similar documents to *query*.

    Args:
        query:           Natural language query string.
        k:               Number of results to return.
        where:           Optional metadata filter dict (ChromaDB `where` syntax).
        collection_name: Override the default collection name.

    Returns:
        List of dicts: [{ "document": str, "metadata": dict, "distance": float }]
    """
    collection = get_or_create_collection(collection_name)

    if collection.count() == 0:
        logger.warning("similarity_search: collection is empty.")
        return []

    query_embedding = embedder_svc.embed_single(query)

    kwargs: Dict[str, Any] = dict(
        query_embeddings=[query_embedding],
        n_results=min(k, collection.count()),
        include=["documents", "metadatas", "distances"],
    )
    if where:
        kwargs["where"] = where

    results = collection.query(**kwargs)

    output: List[Dict[str, Any]] = []
    for doc, meta, dist in zip(
        results["documents"][0],
        results["metadatas"][0],
        results["distances"][0],
    ):
        output.append({"document": doc, "metadata": meta or {}, "distance": dist})

    return output


def delete_collection(collection_name: Optional[str] = None) -> None:
    """
    Delete a ChromaDB collection entirely.

    Args:
        collection_name: Override the default collection name.
    """
    settings = get_settings()
    name = collection_name or settings.chroma_collection_name
    client = _get_client()
    client.delete_collection(name)
    logger.info(f"Deleted collection '{name}'.")


def get_collection_stats(collection_name: Optional[str] = None) -> Dict[str, Any]:
    """
    Return basic statistics about the collection.

    Returns:
        { "count": int, "name": str, "metadata": dict }
    """
    collection = get_or_create_collection(collection_name)
    return {
        "count": collection.count(),
        "name": collection.name,
        "metadata": collection.metadata or {},
    }


def get_all_anomalies(
    limit: int = 50,
    offset: int = 0,
    min_score: float = 0.0,
    collection_name: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Retrieve documents flagged as anomalies.

    Args:
        limit:    Max results to return.
        offset:   Pagination offset.
        min_score: Minimum |anomaly_score| to include.

    Returns:
        { "ids": [...], "documents": [...], "metadatas": [...] }
    """
    collection = get_or_create_collection(collection_name)

    where_filter: Dict[str, Any] = {"is_anomaly": True}

    try:
        results = collection.get(
            where=where_filter,
            limit=limit + offset,
            include=["documents", "metadatas"],
        )
    except Exception as exc:  # noqa: BLE001
        logger.warning(f"get_all_anomalies failed: {exc}")
        return {"ids": [], "documents": [], "metadatas": []}

    # Manual pagination (ChromaDB doesn't natively support offset in .get())
    ids       = results["ids"][offset:]
    docs      = results["documents"][offset:]
    metas     = results["metadatas"][offset:]

    # Apply min_score filter
    filtered = [
        (i, d, m)
        for i, d, m in zip(ids, docs, metas)
        if abs(float(m.get("anomaly_score", 0.0))) >= min_score
    ]

    return {
        "ids":       [t[0] for t in filtered],
        "documents": [t[1] for t in filtered],
        "metadatas": [t[2] for t in filtered],
    }
