"""
ChromaDB vector store service.

Provides CRUD operations over a local persistent ChromaDB collection
using embeddings generated by the embedder service.

Performance notes:
  - The ChromaDB client is a module-level singleton (thread-safe via double-
    checked locking).
  - Collection objects are cached by name after the first
    get_or_create_collection() call.  The cache is invalidated whenever
    add_documents() successfully writes new data so that count() reflects
    the latest state.
"""

from __future__ import annotations

import threading
import uuid
from typing import Any, Dict, List, Optional

import chromadb
from chromadb.config import Settings as ChromaSettings

from app.core.config import get_settings
from app.core.logger import get_logger
from app.services import embedder as embedder_svc

logger = get_logger(__name__)

# ── Module-level singletons ───────────────────────────────────────────────────
_client: Optional[chromadb.PersistentClient] = None
_client_lock = threading.Lock()

# Collection cache — keyed by collection name.
# Storing the chromadb.Collection object avoids a round-trip to the client
# on every vector operation.
_collection_cache: Dict[str, chromadb.Collection] = {}
_collection_cache_lock = threading.Lock()


def _get_client() -> chromadb.PersistentClient:
    """Return (or create) the persistent ChromaDB client (thread-safe)."""
    global _client
    if _client is None:
        with _client_lock:
            if _client is None:  # double-checked locking
                settings = get_settings()
                persist_dir = settings.chroma_persist_dir
                logger.info(f"Connecting to ChromaDB at: {persist_dir}")
                _client = chromadb.PersistentClient(
                    path=persist_dir,
                    settings=ChromaSettings(anonymized_telemetry=False),
                )
    return _client


def _invalidate_collection_cache(name: str) -> None:
    """Remove *name* from the collection cache (e.g. after a write)."""
    with _collection_cache_lock:
        _collection_cache.pop(name, None)


def get_or_create_collection(name: Optional[str] = None) -> chromadb.Collection:
    """
    Return an existing ChromaDB collection or create it if absent.

    The result is cached so subsequent calls do not round-trip to ChromaDB.

    Args:
        name: Collection name (defaults to CHROMA_COLLECTION_NAME from config).

    Returns:
        chromadb.Collection instance.
    """
    settings = get_settings()
    collection_name = name or settings.chroma_collection_name

    # Fast path — return cached collection
    with _collection_cache_lock:
        if collection_name in _collection_cache:
            return _collection_cache[collection_name]

    # Slow path — ask ChromaDB and populate cache
    client = _get_client()
    collection = client.get_or_create_collection(
        name=collection_name,
        metadata={"hnsw:space": "cosine"},  # cosine similarity
    )
    logger.debug(f"Using collection '{collection_name}' ({collection.count()} docs)")

    with _collection_cache_lock:
        _collection_cache[collection_name] = collection

    return collection


def add_documents(
    chunks: List[str],
    metadatas: List[Dict[str, Any]],
    ids: Optional[List[str]] = None,
    collection_name: Optional[str] = None,
) -> None:
    """
    Embed and store text chunks in ChromaDB.

    - Generates embeddings in one batch call.
    - Inserts in groups of 100 to avoid memory spikes.
    - Deduplicates by ID (existing IDs are skipped).
    - Invalidates the collection cache after a successful write.

    Args:
        chunks:          Text strings to embed and store.
        metadatas:       One metadata dict per chunk.
        ids:             Optional explicit IDs; auto-generated (UUID4) if omitted.
        collection_name: Override the default collection name.
    """
    if not chunks:
        logger.warning("add_documents called with empty chunks list — nothing to do.")
        return

    if len(chunks) != len(metadatas):
        raise ValueError(
            f"chunks ({len(chunks)}) and metadatas ({len(metadatas)}) must have the same length."
        )

    # Auto-generate IDs if not provided
    if ids is None:
        ids = [str(uuid.uuid4()) for _ in chunks]
    elif len(ids) != len(chunks):
        raise ValueError(
            f"ids ({len(ids)}) and chunks ({len(chunks)}) must have the same length."
        )

    settings = get_settings()
    cname = collection_name or settings.chroma_collection_name
    collection = get_or_create_collection(cname)

    # Deduplicate: find which IDs already exist
    existing_ids: set[str] = set()
    try:
        existing = collection.get(ids=ids, include=[])
        existing_ids = set(existing["ids"])
    except Exception:  # noqa: BLE001
        pass  # collection may be empty; proceed

    new_mask = [i for i, doc_id in enumerate(ids) if doc_id not in existing_ids]
    if not new_mask:
        logger.info("All documents already exist in collection — skipping insert.")
        return

    new_chunks    = [chunks[i]    for i in new_mask]
    new_metadatas = [metadatas[i] for i in new_mask]
    new_ids       = [ids[i]       for i in new_mask]

    logger.info(f"Embedding {len(new_chunks)} new chunks (batch size 100)…")

    BATCH_SIZE = 100
    for batch_start in range(0, len(new_chunks), BATCH_SIZE):
        batch_chunks    = new_chunks[batch_start : batch_start + BATCH_SIZE]
        batch_metas     = new_metadatas[batch_start : batch_start + BATCH_SIZE]
        batch_ids       = new_ids[batch_start : batch_start + BATCH_SIZE]

        batch_embeddings = embedder_svc.embed(batch_chunks)

        collection.add(
            documents=batch_chunks,
            embeddings=batch_embeddings,
            metadatas=batch_metas,
            ids=batch_ids,
        )
        logger.debug(
            f"  Inserted batch {batch_start // BATCH_SIZE + 1} "
            f"({len(batch_chunks)} docs)"
        )

    logger.info(f"Stored {len(new_chunks)} new documents in ChromaDB.")

    # Invalidate cached collection so get_collection_stats() reflects the new count
    _invalidate_collection_cache(cname)


def similarity_search(
    query: str,
    k: int = 5,
    where: Optional[Dict[str, Any]] = None,
    collection_name: Optional[str] = None,
) -> List[Dict[str, Any]]:
    """
    Search the collection for the *k* most similar documents to *query*.

    Args:
        query:           Natural language query string.
        k:               Number of results to return.
        where:           Optional metadata filter dict (ChromaDB `where` syntax).
        collection_name: Override the default collection name.

    Returns:
        List of dicts: [{ "document": str, "metadata": dict, "distance": float }]
    """
    collection = get_or_create_collection(collection_name)

    if collection.count() == 0:
        logger.warning("similarity_search: collection is empty.")
        return []

    query_embedding = embedder_svc.embed_single(query)

    kwargs: Dict[str, Any] = dict(
        query_embeddings=[query_embedding],
        n_results=min(k, collection.count()),
        include=["documents", "metadatas", "distances"],
    )
    if where:
        kwargs["where"] = where

    results = collection.query(**kwargs)

    output: List[Dict[str, Any]] = []
    for doc, meta, dist in zip(
        results["documents"][0],
        results["metadatas"][0],
        results["distances"][0],
    ):
        output.append({"document": doc, "metadata": meta or {}, "distance": dist})

    return output


def delete_collection(collection_name: Optional[str] = None) -> None:
    """Delete a ChromaDB collection entirely."""
    settings = get_settings()
    name = collection_name or settings.chroma_collection_name
    client = _get_client()
    client.delete_collection(name)
    _invalidate_collection_cache(name)
    logger.info(f"Deleted collection '{name}'.")


def get_collection_stats(collection_name: Optional[str] = None) -> Dict[str, Any]:
    """
    Return basic statistics about the collection.

    Returns:
        { "count": int, "name": str, "metadata": dict }
    """
    collection = get_or_create_collection(collection_name)
    return {
        "count": collection.count(),
        "name": collection.name,
        "metadata": collection.metadata or {},
    }


def get_all_anomalies(
    limit: int = 50,
    offset: int = 0,
    min_score: float = 0.0,
    upload_id: Optional[str] = None,
    collection_name: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Retrieve documents flagged as anomalies.

    Args:
        limit:     Max results to return.
        offset:    Pagination offset.
        min_score: Minimum |anomaly_score| to include.

    Returns:
        { "ids": [...], "documents": [...], "metadatas": [...] }
    """
    collection = get_or_create_collection(collection_name)

    filters: List[Dict[str, Any]] = [{"is_anomaly": True}]
    if upload_id:
        filters.append({"upload_id": upload_id})
    where_filter: Dict[str, Any] = filters[0] if len(filters) == 1 else {"$and": filters}

    try:
        results = collection.get(
            where=where_filter,
            limit=limit + offset,
            include=["documents", "metadatas"],
        )
    except Exception as exc:  # noqa: BLE001
        logger.warning(f"get_all_anomalies failed: {exc}")
        return {"ids": [], "documents": [], "metadatas": []}

    # Manual offset (ChromaDB .get() does not natively support it)
    ids   = results["ids"][offset:]
    docs  = results["documents"][offset:]
    metas = results["metadatas"][offset:]

    # Apply min_score filter
    if min_score > 0.0:
        filtered = [
            (i, d, m)
            for i, d, m in zip(ids, docs, metas)
            if abs(float(m.get("anomaly_score", 0.0))) >= min_score
        ]
        return {
            "ids":       [t[0] for t in filtered],
            "documents": [t[1] for t in filtered],
            "metadatas": [t[2] for t in filtered],
        }

    return {"ids": ids, "documents": docs, "metadatas": metas}


def count_anomalies(
    min_score: float = 0.0,
    upload_id: Optional[str] = None,
    collection_name: Optional[str] = None,
) -> int:
    """
    Return the total count of anomalous documents without fetching their content.

    Args:
        min_score: Minimum |anomaly_score| to include in the count.

    Returns:
        Integer count of matching anomalous documents.
    """
    collection = get_or_create_collection(collection_name)
    filters: List[Dict[str, Any]] = [{"is_anomaly": True}]
    if upload_id:
        filters.append({"upload_id": upload_id})
    where_filter: Dict[str, Any] = filters[0] if len(filters) == 1 else {"$and": filters}
    try:
        if min_score <= 0.0:
            # Fast path: fetch only IDs — skip document / metadata bytes
            results = collection.get(where=where_filter, include=[])
            return len(results["ids"])
        else:
            # Need metadata for score filtering
            results = collection.get(
                where=where_filter,
                include=["metadatas"],
            )
            return sum(
                1 for m in results["metadatas"]
                if abs(float(m.get("anomaly_score", 0.0))) >= min_score
            )
    except Exception as exc:  # noqa: BLE001
        logger.warning(f"count_anomalies failed: {exc}")
        return 0


def count_documents(
    upload_id: Optional[str] = None,
    collection_name: Optional[str] = None,
) -> int:
    """Return document count, optionally restricted to one upload."""
    collection = get_or_create_collection(collection_name)
    if not upload_id:
        return collection.count()

    try:
        results = collection.get(where={"upload_id": upload_id}, include=[])
        return len(results["ids"])
    except Exception as exc:  # noqa: BLE001
        logger.warning(f"count_documents failed: {exc}")
        return 0
